### ISSUE TITLE
Module d'impression

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#6]
Un module d'impression est demandé par le service voies navigable de la région Bretagne.

A minima, création d'un bouton permettant la génération d'un pdf (ou d'une image) sous la forme d'un imprim écran propre : sans les boutons autour.

**Comment by spelhate** [comment]
Work in progress

**Comment by jusabatier** [comment]
I tried to make the print fuction working,

The big problem is to print huge canvas, I had empty map and legends params in the POST request to print.php

I solved this by set generated image to JPEG format (toDataURL, file_put_contents and html loading in print.html) and it allow to print maps with more datas than in PNG

Probably because JPEG encoding miss the alpha value so is lighter than PNG

**Comment by pierrejego** [comment]
Hello, two others solution are in progress, Rennes Metropole will create a PR shortly with one of this solution

**Comment by Gaetanbrl** [comment]
@lecault tu as reproduis cette erreur depuis 2015 ?

**Comment by lecault** [comment]
Ce n'est pas une erreur mais une demande. 
On a juste fait un imprim écran amélioré au niveau de la région

**Comment by Gaetanbrl** [comment]
pardon @lecault  c'est @jusabatier qui avait remonté une erreur. Il semble que nous en rencontrions un similaire.

**Comment by jusabatier** [comment]
De mémoire, le problème semblait venir du javascript qui n'envoyait pas de paramètres au script php générant la page.

Une solution était de forcer le format de l'image à JPG, ce qui me fait penser à un souci de gestion avec le PNG.

Je n'ai pas re-testé depuis

**Comment by Gaetanbrl** [comment]
On peut clore @lecault ?
