### ISSUE TITLE
Outil de dessin simple

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#904]
**Présentation**

Des utilisateurs ont besoin d'avoir un outil de dessin simple qui reprend le fonctionnement de cet outil :

https://earth.google.com/web/@0,-1.52290015,0a,22251752.77375655d,35y,0h,0t,0r/data=OgMKATA

**Description fonctionnelle**

Voici un cas d'usage :

- Ouvrir mviewer
- Cliquer sur l'outil "dessin" dans la barre d'outil (sous l'outil de mesure) type polygone
- Le mode dessin s'active -> Le clic de la souris permet de poser des noeuds / arcs
- La mesure de surface / linéaire s'affiche en direct soit dans une popup soit dans une fenêtre dédiée
- Un bouton "Exporter" est disponible à tout moment et permet de Télécharger la forme en cours de dessin (en GeoJSON au moins)
- L'utilisateur peut continuer de modifier la forme en cours de dessin et Télécharger autant de fois que nécessaire
- L'utilisateur peut s'accrocher à un WMS (snapping) pour faciliter la précision du dessin (ex: accroche sur le parcellaire)

**Description technique**

Le code intègrera le coeur mviewer en tant que nouvel outil comme l'outil de mesure.

Cela nécessite : 

- D'ajouter un control de dessin à la carte lors du chargement du mviewer
- D'ajouter une couche (overlay) lors du chargement du mviewer
- D'ajouter un style dédié
- D'avoir une interface permettant d'afficher un bouton d'export
- D'avoir une interface permettant d'afficher une information sur la mesure en cours de dessin
- D'avoir une interface permettant de choisir la couche d'accroche (pour activer ou non le snapping -> Pas d'autres options pour une v1)
- D'avoir une interface permettant de supprimer la forme en cours de dessin (reset)
- D'avoir une interface pour désactiver l'outil de dessins
- D'avoir une interface pour choisir la forme dessinée (linéaire / polygon)

**L'outil doit être simple et ne doit pas comporter d'appel type service API / stockage en bas.**

**Comment by Doctor-Who** [comment]
Bonjour @Gaetanbrl 

Je suis très intéressé par cet outil pour un cas d'usage imminent : l'instruction des projets d'envergure régionale qui seront décomptés de la consommation foncière des territoires dans le cadre du ZAN.

Le logiciel d'instruction ne propose pas de fonctionnalités de dessin ou cartographie, et les utilisateurs chargés de saisir les demandes n'ont pas de formation en géomatique. Ils doivent pouvoir ajouter des documents en pièce jointe.

Nous avons besoin du contour du projet sur un fond cadastral pour assurer la cohérence entre l'enveloppe déclarée et le projet, et pour croiser avec des indicateurs SIG sans ressaisir les données à partir de plans PDF.

J'apprécie particulièrement la simplicité de l'outil de dessin d'Earth (version web). Concernant les fonctionnalités, je partage tes observations et ajoute quelques précisions :

- Le fait qu'Earth ajoute automatiquement un nœud au milieu de chaque segment facilite la reprise du zonage, évitant d'introduire un nouvel item de menu "ajout nœud" peu intuitif, et penser que les personnes savent intuitivement que le double clic ajoute un nœud.
- Les tooltips "sélectionner le point de départ" et "fermer la forme" sont très utiles.
- Dans la fenêtre affichant le périmètre, il est mentionné de cliquer sur la carte pour ajouter un polygone.

Après discussion avec mon responsable, nous sommes potentiellement intéressés à financer cette fonctionnalité. 🎉

**Comment by Gaetanbrl** [comment]
Cette méthode devrait permettre de dessiner les noeuds médian : 

```
  draw.on("drawend", (event) => {
    let line = event.feature.getGeometry();
    let coordinates = line.getCoordinates();
    // calculate median coordinates for each segment
    for (let i = 0; i < coordinates.length - 1; i++) {
      let start = coordinates[i];
      let end = coordinates[i + 1];
  
      // calculate median point coordinates
      let midpoint = [
        (start[0] + end[0]) / 2,
        (start[1] + end[1]) / 2
      ];
  
      // add median point
      let pointFeature = new Feature(new Point(midpoint));
      // add point to vector layer source
      source.addFeature(pointFeature);
    }
  })
```

**Comment by pierrejego** [comment]
@Doctor-Who tu parles pouvoir ajouter des documents en pièce jointe. On est d'accord ce n'est pas du tout dans le scope de cette issue

**Comment by Doctor-Who** [comment]
@pierrejego 
C'est le logiciel d'instruction qui attend une PJ (la description du contexte manque peut être de clarté). 
Je te confirme que ce n'est pas dans le scope de cette issue.
En revanche, la fonctionnalité ici présente doit proposer un export du tracé à minima en GeoJSON.

**Comment by pierrejego** [comment]
Début de développement en cours, démo disponible ici  https://gis.jdev.fr/mviewerjdev/?config=demo/draw.xml

**Comment by pierrejego** [comment]
Deux démos sont disponibles avec des options différentes : 
https://gis.jdev.fr/mviewerjdev/?config=demo/draw/draw.xml
https://gis.jdev.fr/mviewerjdev/?config=demo/draw/draw2.xml

Pour l'export en geojson, la RFC du geojson a changé. https://datatracker.ietf.org/doc/html/rfc7946

Note: the use of alternative coordinate reference systems was
   specified in [[GJ2008](https://datatracker.ietf.org/doc/html/rfc7946#ref-GJ2008)], but it has been removed from this version of
   the specification because the use of different coordinate reference
   systems -- especially in the manner specified in [[GJ2008](https://datatracker.ietf.org/doc/html/rfc7946#ref-GJ2008)] -- has
   proven to have interoperability issues.  In general, GeoJSON
   processing software is not expected to have access to coordinate
   reference system databases or to have network access to coordinate
   reference system transformation parameters.  However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.

Il n'y a donc plus dans le standard du geojson la possibilité de mettre la projection correspondante aux données, les données doivent être en WGS84. 
L'outil d'export reprojette donc de la projection du mviewer vers du WGS84.
